# Generated by Django 4.0.3 on 2022-03-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('room', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('intime', models.TimeField()),
                ('outtime', models.TimeField()),
                ('relation', models.TextField()),
            ],
        ),
    ]
