# Generated by Django 4.0.2 on 2022-04-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='certi',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='aadhar',
            field=models.IntegerField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='allergy',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='aphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='blood',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='caste',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email1',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email2',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='gaddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='gnumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='guard',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='hometown',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mob',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mob1',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mob2',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='nation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='pan',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='rel',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sphoto',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='svaccine',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
