# Generated by Django 4.0.2 on 2022-05-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_rename_year_studentdetails_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='aphoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='certi',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sphoto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='svaccine',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
