# Generated by Django 4.0.2 on 2022-05-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_alter_studentdetails_aphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='aphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='certi',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='lname',
            field=models.CharField(default=' ', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='svaccine',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
