# Generated by Django 4.0.2 on 2022-05-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_alter_studentdetails_aphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='sphoto',
        ),
    ]
