# Generated by Django 4.0.2 on 2022-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_remove_studentdetails_sphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='sphoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
