# Generated by Django 4.0.2 on 2022-05-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_studentdetails_sphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='certi',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
