# Generated by Django 4.0.2 on 2022-05-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_studentdetails_certi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='aphoto',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='sphoto',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='svaccine',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
